codecov:
  notify:
    require_ci_to_pass: yes
  branch: main

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 80%
        if_ci_failed: error
        informational: false
        only_pulls: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/__tests__/**/*"
  - "**/*.test.ts"
  - "**/examples/**/*"
  - "dist/**/*"
  - "coverage/**/*"

flags:
  unittests:
    paths:
      - src/
    carryforward: true