coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true

ignore:
  - "**/__tests__/**/*"
  - "**/*.test.ts"
  - "**/examples/**/*"
  - "dist/**/*"
  - "coverage/**/*"